### ISSUE TITLE
Duplicate logging emitted on start/end

### ISSUE THREAD

**Issue by perlun** [dmitryshindin/karma-jasmine-order-reporter#2]
Hi,

Thanks for a nice Karma plugin. When enabling this, I get duplicate entries logged on start and end of the test run though:

```
Chrome Headless 89.0.4389.114 (Linux x86_64) JASMINE ORDER REPORTER LOG: Started with seed 77398
Chrome Headless 89.0.4389.114 (Linux x86_64) JASMINE ORDER REPORTER: Started with seed 77398

[...]

JASMINE ORDER REPORTER LOG: Done with seed 77398
JASMINE ORDER REPORTER: Done with seed 77398
```

The first and third entries are coloured and the others are not. Is there any way to get rid of that extra logging? We run these tests with `logLevel: config.LOG_INFO` and with `HeadlessChrome` as the browser. Can provide more details about our config if needed.

**Comment by dmitryshindin** [comment]
Hi @perlun. 
It would be great if you provide more info about other reporters you use.

As I remember this issue occurs when you use `karma-jasmine-html-reporter`.

**Comment by perlun** [comment]
Sure. Here are the plugins & reporters we use at the moment:

```javascript
    {
        plugins: [
            'karma-chrome-launcher',
            'karma-coverage',
            'karma-jasmine',
            'karma-jasmine-order-reporter',
            'karma-spec-reporter'
        ],

        reporters: [
            'coverage',
            'spec',
            'jasmine-order'
        ],
    }
```

**Comment by dmitryshindin** [comment]
@perlun Thank you for providing your config. I was able to reproduce and fix this issue. 
Please update your package to the latest version (1.1.0)

**Comment by perlun** [comment]
Thanks @dmitryshindin, I can verify that the fix works in our code base as well. Appreciated! :pray:

**Comment by ToadJamb** [comment]
I am seeing duplicate error information and log output when using this in combination with the `progress` reporter. I would just drop the `progress` reporter to fix it, but the `progress` reporter provides colorized output which makes visually parsing output much easier during debugging.
