### ISSUE TITLE
Duplicate logging when used with "dots" reporter

### ISSUE THREAD

**Issue by briandipalma** [dmitryshindin/karma-jasmine-order-reporter#4]
We're seeing the same as #3 but for every log line when using the dots reporter, I wonder if blanking out the logging function like:

https://github.com/angular/angular-cli/pull/9529/files

would fix it?

**Comment by dmitryshindin** [comment]
Hi @briandipalma. Could you please provide more details about your environment, including version of order-reporter package and `reporters` property in `karma.conf.js`?

I tried to reproduce it, however, I don't see the issue you described

**Comment by dmitryshindin** [comment]
Closed via #5
